In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3])
print(np.cumsum(arr))



[1 3 6]


In [3]:
arr1d=np.arange(43)

In [4]:
arr1d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42])

In [6]:
arr1d.size

43

In [7]:
arr1d.shape

(43,)

In [8]:
arr1d.dtype

dtype('int32')

In [11]:
arr=np.array([1,2,3,0.5,8,9,"jiya"])

In [12]:
arr.dtype

dtype('<U32')

In [13]:
arr1d.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42])

In [20]:
arr=np.array([[0.5,8,9,"jiya"],["bia",6,7,9]])# should have same data elemts

In [21]:
arr

array([['0.5', '8', '9', 'jiya'],
       ['bia', '6', '7', '9']], dtype='<U32')

In [22]:
ar=np.arange(10).reshape(2,5)

In [23]:
ar

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [26]:
ar.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
x=np.array([1,6,8,9,4,4,3])

In [28]:
x

array([1, 6, 8, 9, 4, 3])

In [30]:
np.where(x==4)

(array([4], dtype=int64),)

In [42]:
arr3d=np.arange(64).reshape(2,8,4)

In [43]:
arr3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47],
        [48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [44]:
arr3d[:3,1:4,1:3]

array([[[ 5,  6],
        [ 9, 10],
        [13, 14]],

       [[37, 38],
        [41, 42],
        [45, 46]]])

In [46]:
arr2d=np.arange(20).reshape(4,5)

In [47]:
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [48]:
arr2d[1:3,:]

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [49]:
arr2d[1:3,:3]

array([[ 5,  6,  7],
       [10, 11, 12]])

In [51]:
y=np.arange(30).reshape(3,10)

In [52]:
y

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [53]:
z=np.arange(20).reshape(2,10)

In [54]:
z

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [58]:
np.hstack(y)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [60]:
np.stack(z)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [61]:
np.hstack(z)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [62]:
np.concatenate((z,y))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [63]:
np.stack((z,y)) #should have same shape

ValueError: all input arrays must have the same shape

In [66]:
l=np.arange(20).reshape(2,10)

In [67]:
l

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [69]:
np.add(l,z)

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38]])

In [70]:
np.subtract(l,z)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [72]:
l*z

array([[  0,   1,   4,   9,  16,  25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196, 225, 256, 289, 324, 361]])

In [73]:
np.hstack((l,z))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9,  0,  1,  2,  3,  4,  5,
         6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19]])