In [92]:
import numpy as np

In [93]:
# convert 1D TO 2D ARRAY 1
array=np.arange(10).reshape(2,5)
array


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [94]:
array=np.array([0,1,2,3,4,5,6,7,8,9])

In [95]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [96]:
array.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [97]:
# Q 2 
# how to stack two arrays vertically
""" for this both array should have same shape"""
array1=np.arange(10).reshape(2,5)
array1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [98]:
array2=np.ones((2,5))
array2=array2.astype(int)# astype is use to convert floating to integer 
array2

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [99]:
arr3=np.vstack((array1,array2))

In [100]:
arr3

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [101]:
# question 3
arr4=np.hstack((array1,array2))

In [102]:
arr4

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [103]:
# increasein no of dimension 
arr5=np.stack((array1,array2))# to make more dimension or increase dimension it work as a fold

In [104]:
arr5 

array([[[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

In [105]:
# question no 4
array1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [106]:
# use of flatten()

In [107]:
array1.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [108]:
#question no 5
array6=np.arange(15).reshape(5,3,1)

In [109]:
array6

array([[[ 0],
        [ 1],
        [ 2]],

       [[ 3],
        [ 4],
        [ 5]],

       [[ 6],
        [ 7],
        [ 8]],

       [[ 9],
        [10],
        [11]],

       [[12],
        [13],
        [14]]])

In [110]:
array6.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [111]:
#question no 6
#convert one dimension array to higher dimension
arr=np.array([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14]).reshape(5,3)
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [112]:
# question no 7
#make array 5x5 array and find square
arr=np.arange(25).reshape(5,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [113]:
np.square(arr)# 

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]])

In [114]:
#question no 8
arr=np.arange(30).reshape(5,6)
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [115]:
np.mean(arr)

14.5

In [116]:
# QUESTION NO 9
# find standard devaition of previous array
np.std(arr)

8.65544144839919

In [117]:
# QUESTION NO 10
np.median(arr)

14.5

In [118]:
# QUESTION NO 11
np.transpose(arr)

array([[ 0,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]])

In [119]:
# QUESTION NO 12
# find the sum of diagonal elemts of 4X4 array by use of np.trace(name of array)metod
arr=np.arange(16).reshape(4,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [120]:
np.trace(arr)

30

In [121]:
arr1=np.arange(20).reshape(5,4)
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [122]:
np.trace(arr1)

30

In [123]:
# what if we want to change the axis directiom # use flip()method
dg_sum=np.trace(np.flip(arr1,axis=0))
# first it will flip the diagonal and then make another diagonal 
"""[[16, 17, 18, 19],
   [12, 13, 14, 15],
   [ 8,  9, 10, 11],
   [ 4,  5,  6,  7],
   [ 0,  1,  2,  3]]
 it will flip like this now main diagonal is [16 13 10 7]"""

'[[16, 17, 18, 19],\n   [12, 13, 14, 15],\n   [ 8,  9, 10, 11],\n   [ 4,  5,  6,  7],\n   [ 0,  1,  2,  3]]\n it will flip like this now main diagonal is [16 13 10 7]'

In [124]:
dg_sum

46

In [125]:
#QUESTION NO 13
# FIND DETERMINNAT
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [126]:
np.linalg.det(arr)


0.0

In [127]:
# question no 14
# find the 5th and 95th percintels
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [128]:
np.percentile(arr,5)

0.75

In [129]:
np.percentile(arr,95)

14.25

In [130]:
#QUESTION NO 15
arr


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [131]:
np.isnan(arr).any()

False

In [132]:
arr=np.array([0,1,2,3,4,5,np.nan,8,9,10])

In [133]:
arr

array([ 0.,  1.,  2.,  3.,  4.,  5., nan,  8.,  9., 10.])

In [134]:
has_null=np.isnan(arr).any()
if has_null:
    print("have")
else:
    print("no")

have
