In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [1]:
import numpy as np

In [2]:
x=np.array([22,23,76,45,90,15])

In [4]:
x

array([22, 23, 76, 45, 90, 15])

In [5]:
x.ndim

1

In [6]:
x.shape

(6,)

In [7]:
x.size # multiple both row with ccolumn

6

arange

In [9]:
arr1d=np.arange(10)

In [10]:
arr1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
arr2d=np.array([[1,2,3],[2,4,6],[7,7,8]])

In [13]:
arr2d

array([[1, 2, 3],
       [2, 4, 6],
       [7, 7, 8]])

In [14]:
arr2d=np.array([[1,2,3],[2,4,6],[7,7,8,9,0]])# will generate errr should have same sequence

/tmp/ipykernel_32/1733572123.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr2d=np.array([[1,2,3],[2,4,6],[7,7,8,9,0]])


creating 2d array through arange

In [16]:
arr2d=np.arange(20).reshape(20,1)

In [17]:
arr2d

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19]])

In [18]:
#can generate array through sequence should have parameters in reshape equal to range 
arr2d=np.arange(20).reshape(5,4)# as 5 x 4 = 20 
arr2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [21]:
# conversion of 2d to 1d 
arr2d.reshape(20)
arr2d
arr2d.reshape(5,4)
arr2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [23]:
arr2d.flatten()# make any dimension to 1D

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [27]:
#genetation of 3d array 
arr3d=np.arange(64).reshape(4,4,4)# first value give
#depth,second give row and third one give colimn
arr3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [32]:
arr3d=np.arange(64).reshape(8,2,4)# reshape parameters should satisifed the arange value
arr3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39]],

       [[40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55]],

       [[56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [34]:
#indexing of 2d
arr2d[2,2]

10

In [36]:
arr2d=np.arange(30).reshape(5,6)
arr2d

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [38]:
arr2d[3,5]# first give the value or row then give the value of column 

23

In [40]:
arr3d[0]# give complete matrix at 0 index 

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [41]:
arr3d[1]

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [43]:
# specified element finding method
arr3d[2,1,3]# at index 2 matrix of index 1 row of 3 index column value

23

In [44]:
arr3d[2]

array([[16, 17, 18, 19],
       [20, 21, 22, 23]])

In [48]:
x=np.arange(20).reshape(5,4)

In [49]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [50]:
x*2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22],
       [24, 26, 28, 30],
       [32, 34, 36, 38]])

In [51]:
x**2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121],
       [144, 169, 196, 225],
       [256, 289, 324, 361]])

In [52]:
x/3

array([[0.        , 0.33333333, 0.66666667, 1.        ],
       [1.33333333, 1.66666667, 2.        , 2.33333333],
       [2.66666667, 3.        , 3.33333333, 3.66666667],
       [4.        , 4.33333333, 4.66666667, 5.        ],
       [5.33333333, 5.66666667, 6.        , 6.33333333]])

In [56]:
x-2

array([[-2, -1,  0,  1],
       [ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13],
       [14, 15, 16, 17]])

In [57]:
x-4-8

array([[-12, -11, -10,  -9],
       [ -8,  -7,  -6,  -5],
       [ -4,  -3,  -2,  -1],
       [  0,   1,   2,   3],
       [  4,   5,   6,   7]])

In [63]:
# shorthand method to multiply specified digit
arr3d[4,1,3]=arr3d[4,1,3]*5
arr3d[4,1,3]

4875

In [61]:
arr3d

array([[[  0,   1,   2,   3],
        [  4,   5,   6,   7]],

       [[  8,   9,  10,  11],
        [ 12,  13,  14,  15]],

       [[ 16,  17,  18,  19],
        [ 20,  21,  22,  23]],

       [[ 24,  25,  26,  27],
        [ 28,  29,  30,  31]],

       [[ 32,  33,  34,  35],
        [ 36,  37,  38, 195]],

       [[ 40,  41,  42,  43],
        [ 44,  45,  46,  47]],

       [[ 48,  49,  50,  51],
        [ 52,  53,  54,  55]],

       [[ 56,  57,  58,  59],
        [ 60,  61,  62,  63]]])

In [64]:
#addition of two arrays 
# shape should be equal 
#mirroring or lement wise addition of an elements 
a=np.arange(25).reshape(5,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [65]:
b=np.arange(25).reshape(5,5)
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [66]:
a+b

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48]])

In [67]:
a-b

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [68]:
a*b

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]])

In [69]:
a@b

array([[ 150,  160,  170,  180,  190],
       [ 400,  435,  470,  505,  540],
       [ 650,  710,  770,  830,  890],
       [ 900,  985, 1070, 1155, 1240],
       [1150, 1260, 1370, 1480, 1590]])

In [71]:
# np.matmul(),np.dot() use for same purprse
np.matmul(a,b)

array([[ 150,  160,  170,  180,  190],
       [ 400,  435,  470,  505,  540],
       [ 650,  710,  770,  830,  890],
       [ 900,  985, 1070, 1155, 1240],
       [1150, 1260, 1370, 1480, 1590]])

In [73]:
np.dot(a,b)

array([[ 150,  160,  170,  180,  190],
       [ 400,  435,  470,  505,  540],
       [ 650,  710,  770,  830,  890],
       [ 900,  985, 1070, 1155, 1240],
       [1150, 1260, 1370, 1480, 1590]])

In [79]:
 # to find inverse of matrix should have square matrix
np.linalg.inv([[1,2],[3,4]])

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [82]:
a=arr3d
a

array([[[   0,    1,    2,    3],
        [   4,    5,    6,    7]],

       [[   8,    9,   10,   11],
        [  12,   13,   14,   15]],

       [[  16,   17,   18,   19],
        [  20,   21,   22,   23]],

       [[  24,   25,   26,   27],
        [  28,   29,   30,   31]],

       [[  32,   33,   34,   35],
        [  36,   37,   38, 4875]],

       [[  40,   41,   42,   43],
        [  44,   45,   46,   47]],

       [[  48,   49,   50,   51],
        [  52,   53,   54,   55]],

       [[  56,   57,   58,   59],
        [  60,   61,   62,   63]]])

In [85]:
a[2:3,1,1:4]# firsy the range of depth ,second is the range of row ,
#3 is the range of column

array([[21, 22, 23]])

In [88]:
#querrying array
b=arr2d
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [89]:
a>5

array([[[False, False, False, False],
        [False, False,  True,  True]],

       [[ True,  True,  True,  True],
        [ True,  True,  True,  True]],

       [[ True,  True,  True,  True],
        [ True,  True,  True,  True]],

       [[ True,  True,  True,  True],
        [ True,  True,  True,  True]],

       [[ True,  True,  True,  True],
        [ True,  True,  True,  True]],

       [[ True,  True,  True,  True],
        [ True,  True,  True,  True]],

       [[ True,  True,  True,  True],
        [ True,  True,  True,  True]],

       [[ True,  True,  True,  True],
        [ True,  True,  True,  True]]])

In [90]:
b<0# mask will return the boolean value as compare to True or false

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [91]:
b[b>15] # will return all value greater than 15 

array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [93]:
b[b>20]=101

In [94]:
b

array([[  0,   1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10,  11],
       [ 12,  13,  14,  15,  16,  17],
       [ 18,  19,  20, 101, 101, 101],
       [101, 101, 101, 101, 101, 101]])

In [95]:
# where is used to satisfied the condition +replaceable value + else condition 
np.where(b>20,0,b)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0]])

In [97]:
np.where(b>20,0,"gp")

array([['gp', 'gp', 'gp', 'gp', 'gp', 'gp'],
       ['gp', 'gp', 'gp', 'gp', 'gp', 'gp'],
       ['gp', 'gp', 'gp', 'gp', 'gp', 'gp'],
       ['gp', 'gp', 'gp', '0', '0', '0'],
       ['0', '0', '0', '0', '0', '0']], dtype='<U21')

In [98]:
# can give more than one condition 
a[(a%2==0) &(a%7==0)] # will give all value where condition is satisfied

array([ 0, 14, 28, 42, 56])

In [99]:
b[(b%2==0) |(b%7==0)]

array([ 0,  2,  4,  6,  7,  8, 10, 12, 14, 16, 18, 20])

In [100]:
x=np.where((a%2==0) &(a%7==0))

(array([0, 1, 3, 5, 7]), array([0, 1, 1, 0, 0]), array([0, 2, 0, 2, 0]))

In [102]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [105]:
# combining metrices
a=np.arange(15).reshape(3,5)
b=np.arange(15,30).reshape(3,5)
np.concatenate((a,b),axis=1)# will add in vertical direction

array([[ 0,  1,  2,  3,  4, 15, 16, 17, 18, 19],
       [ 5,  6,  7,  8,  9, 20, 21, 22, 23, 24],
       [10, 11, 12, 13, 14, 25, 26, 27, 28, 29]])

In [106]:
np.stack((a,b))#3d array will formed

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [107]:
np.hstack((a,b))# add horiontal 

array([[ 0,  1,  2,  3,  4, 15, 16, 17, 18, 19],
       [ 5,  6,  7,  8,  9, 20, 21, 22, 23, 24],
       [10, 11, 12, 13, 14, 25, 26, 27, 28, 29]])

In [108]:
np.vstack((a,b))#will add vertically

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [112]:
#any use
((a<5).any())

True