In [1]:
import numpy as np

In [2]:
l=np.array([22,23,44,55])

In [3]:
l

array([22, 23, 44, 55])

In [4]:
m=np.array(9)

In [5]:
m

array(9)

In [6]:
m.ndim# mthod to finding dimension of 

0

In [7]:
l.ndim

1

# features of numpy array 


In [8]:
# size
#shape

In [9]:
m.size

1

In [10]:
l.size

4

In [11]:
l.shape

(4,)

In [12]:
m.shape

()

In [13]:
z=np.array([[1,2,3,5],[8,9,0,4]])

In [14]:
z

array([[1, 2, 3, 5],
       [8, 9, 0, 4]])

In [15]:
z.ndim

2

In [16]:
z.shape

(2, 4)

In [17]:
z.size

8

In [18]:
# in python we use the function of range while in numpy we will use arange

In [19]:
arr1d=np.arange(10)

In [20]:
arr1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
arr1d.size

10

In [22]:
arr1d.ndim

1

In [23]:
arr1d.shape

(10,)

# arange

In [24]:
arr2d=np.arange(16).reshape(2,8)

In [25]:
arr2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [26]:
arr3d=np.arange(48).reshape(4,2,6)# first one gave depth then row and then column

In [27]:
arr3d

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]],

       [[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]],

       [[24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]],

       [[36, 37, 38, 39, 40, 41],
        [42, 43, 44, 45, 46, 47]]])

# again conversion of 2d to 1d

In [30]:
arr2d.reshape(16)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [31]:
arr3d.reshape(48)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47])

# flatten() use

In [32]:
arr2d.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

# indexing

In [33]:
arr2d[1,3]

11

In [34]:
arr2d[1]# will give complete row

array([ 8,  9, 10, 11, 12, 13, 14, 15])

In [35]:
arr3d[0]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [38]:
arr3d[1]

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [39]:
arr3d[0,1,3]# method of accessing specific column

9

In [40]:
arr3d

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]],

       [[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]],

       [[24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]],

       [[36, 37, 38, 39, 40, 41],
        [42, 43, 44, 45, 46, 47]]])

In [41]:
arr3d[2,1,2]# depth,row,column

32

In [42]:
arr2d*3

array([[ 0,  3,  6,  9, 12, 15, 18, 21],
       [24, 27, 30, 33, 36, 39, 42, 45]])

In [43]:
arr2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [44]:
arr2d-7

array([[-7, -6, -5, -4, -3, -2, -1,  0],
       [ 1,  2,  3,  4,  5,  6,  7,  8]])

In [47]:
# method to multiplying a specific element
arr3d[2,1,2]=arr3d[2,1,2]*6

In [48]:
arr3d[2,1,2]

192

In [49]:
arr3d

array([[[  0,   1,   2,   3,   4,   5],
        [  6,   7,   8,   9,  10,  11]],

       [[ 12,  13,  14,  15,  16,  17],
        [ 18,  19,  20,  21,  22,  23]],

       [[ 24,  25,  26,  27,  28,  29],
        [ 30,  31, 192,  33,  34,  35]],

       [[ 36,  37,  38,  39,  40,  41],
        [ 42,  43,  44,  45,  46,  47]]])

# addition of two arrays

In [50]:
l1=np.arange(10,40).reshape(5,6)

In [51]:
l1

array([[10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [55]:
l2=np.arange(41,71).reshape(5,6)

In [56]:
l2

array([[41, 42, 43, 44, 45, 46],
       [47, 48, 49, 50, 51, 52],
       [53, 54, 55, 56, 57, 58],
       [59, 60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69, 70]])

# mirroring or element wise

In [60]:
l1+l2

array([[ 51,  53,  55,  57,  59,  61],
       [ 63,  65,  67,  69,  71,  73],
       [ 75,  77,  79,  81,  83,  85],
       [ 87,  89,  91,  93,  95,  97],
       [ 99, 101, 103, 105, 107, 109]])

In [61]:
l1*l2

array([[ 410,  462,  516,  572,  630,  690],
       [ 752,  816,  882,  950, 1020, 1092],
       [1166, 1242, 1320, 1400, 1482, 1566],
       [1652, 1740, 1830, 1922, 2016, 2112],
       [2210, 2310, 2412, 2516, 2622, 2730]])

In [64]:
l3=np.arange(36).reshape(6,6)

In [65]:
l3

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

# slicing

In [68]:
l1[1:4,2:5]

array([[18, 19, 20],
       [24, 25, 26],
       [30, 31, 32]])

# querrying array

In [69]:
l1>5

array([[ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

In [70]:
l1-l2>9

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [71]:
l1+l2>=0

array([[ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

In [72]:
l1[l1>67]

array([], dtype=int32)

In [73]:
l1[l1<9]

array([], dtype=int32)

In [75]:
l1[l1>1]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [77]:
np.concatenate((l1,l2)) # by default add in rows

array([[10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39],
       [41, 42, 43, 44, 45, 46],
       [47, 48, 49, 50, 51, 52],
       [53, 54, 55, 56, 57, 58],
       [59, 60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69, 70]])

In [78]:
np.concatenate((l1,l2),axis=1)

array([[10, 11, 12, 13, 14, 15, 41, 42, 43, 44, 45, 46],
       [16, 17, 18, 19, 20, 21, 47, 48, 49, 50, 51, 52],
       [22, 23, 24, 25, 26, 27, 53, 54, 55, 56, 57, 58],
       [28, 29, 30, 31, 32, 33, 59, 60, 61, 62, 63, 64],
       [34, 35, 36, 37, 38, 39, 65, 66, 67, 68, 69, 70]])

In [79]:
np.stack((l1,l2)) #will form 3 dimensiom

array([[[10, 11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20, 21],
        [22, 23, 24, 25, 26, 27],
        [28, 29, 30, 31, 32, 33],
        [34, 35, 36, 37, 38, 39]],

       [[41, 42, 43, 44, 45, 46],
        [47, 48, 49, 50, 51, 52],
        [53, 54, 55, 56, 57, 58],
        [59, 60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69, 70]]])

In [81]:
np.stack((l1,l2))# shape shold be same

array([[[10, 11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20, 21],
        [22, 23, 24, 25, 26, 27],
        [28, 29, 30, 31, 32, 33],
        [34, 35, 36, 37, 38, 39]],

       [[41, 42, 43, 44, 45, 46],
        [47, 48, 49, 50, 51, 52],
        [53, 54, 55, 56, 57, 58],
        [59, 60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69, 70]]])

In [82]:
np.hstack((l1,l2))#

array([[10, 11, 12, 13, 14, 15, 41, 42, 43, 44, 45, 46],
       [16, 17, 18, 19, 20, 21, 47, 48, 49, 50, 51, 52],
       [22, 23, 24, 25, 26, 27, 53, 54, 55, 56, 57, 58],
       [28, 29, 30, 31, 32, 33, 59, 60, 61, 62, 63, 64],
       [34, 35, 36, 37, 38, 39, 65, 66, 67, 68, 69, 70]])

# addition/sum

In [83]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Summing along axis=1 (columns)
sum_along_axis1 = np.sum(arr, axis=1)

print(sum_along_axis1)

[ 6 15 24]


In [84]:
k=np.sum(arr,axis=0)

In [85]:
k

array([12, 15, 18])

In [86]:
np.vstack((l1,l2))

array([[10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39],
       [41, 42, 43, 44, 45, 46],
       [47, 48, 49, 50, 51, 52],
       [53, 54, 55, 56, 57, 58],
       [59, 60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69, 70]])

In [88]:
(l1<5).any()

False